version: '3.8'

services:
  editor:
    build:
      context: .
    ports:
      - "8001:8001"
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
